### ISSUE TITLE
Issue with Dockerfile `COPY` without docker-compose `volume`

### ISSUE THREAD

**Issue by waldronfaulkner** [patallen/dc-common-code#1]
Using `COPY` in applications' Dockerfiles works when first built, but subsequent changes to contents of the file are ignored unless there is a corresponding `volume` entry in `docker-compose.yml`.

Because there _is_ a `volume` entry for `common/`, changes to that file do effect files in the running container. But changes in either `application/app.py` or `worker/app.py` won't get reflected until their containers get rebuilt.

Submitting a PR for this in a moment.

**Comment by patallen** [comment]
Fixed in #2
